# this SA is only for workaround for the db migration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: richmond-golang-ledger
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: richmond-golang-ledger-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - jobs
      - namespaces
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: richmond-golang-ledger-role-binding
subjects:
  - kind: ServiceAccount
    name: richmond-golang-ledger
    namespace: richmond-golang-ledger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: richmond-golang-ledger-role
